service:
  prepare:
  - export CGO_ENABLED=1
  - export GOOS=$(go env GOHOSTARCH)
  - export GOARCH=$(go env GOHOSTARCH)

run:
  deadline: 5m
  tests: true
  modules-download-mode: vendor
  skip-dirs:
  - vendor
  - private
  build-tags:
  - containers_image_openpgp

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable-all: true
  disable:
  # All these break for one reason or another
  - dupl
  - funlen
  - gochecknoglobals
  - gochecknoinits
  - goconst
  - gocyclo
  - golint
  - lll
  - structcheck
  - typecheck
  - unconvert
  - varcheck
  - deadcode
  - depguard
  - errcheck
  - gocritic
  - gosec
  - maligned
  - exhaustivestruct
  - wrapcheck
  - wsl
  - gocognit
  - nlreturn
  - godox
  - gomnd
  - nestif
  - goerr113
  - prealloc
  - unused
  - exhaustive

  # enable:
  # - golint
  # - errcheck
  # - misspell
  # - deadcode
  # - govet
  # - typecheck
  # - lll
  # - megacheck
  # - varcheck
  # - unconvert
  # - bodyclose
  # - scopelint
  # - goimports
  # - ineffassign
  # - gofmt
  # - maligned
  # - goconst
  # - gocyclo
  # - unparam
  # - structcheck
  # - staticcheck
  # - gocritic

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  misspell:
    locale: US
  unused:
    check-exported: false
  gocyclo:
    min-complexity: 30
  goimports:
    local-prefixes: ext.arhat.dev/runtime-podman
  lll:
    line-length: 120
    # tab width in spaces. Default to 1.
    tab-width: 4
  maligned:
    suggest-new: true

issues:
  exclude-rules:
  - path: _test\.go
    linters:
    - gocyclo
    - errcheck
    - dupl
    - gosec
    - maligned
    - lll
    - scopelint

  - text: "commentFormatting: put a space between `//` and comment text"
    linters:
    - gocritic
